site_name: KilleenGeo
site_url: https://killeengeo.readthedocs.io/en/latest
nav:
  - Home: index.md

theme:
  name: mkdocs
  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
